output "enabled" {
  description = "Whether the module is enabled."
  value       = local.enabled
}

output "id" {
  description = "The disambiguated ID generated by tf-label (e.g. `eg-test-thing`)."
  value       = module.this.id
}

output "tags" {
  description = "Normalized tag map generated by tf-label and applied to resources."
  value       = local.tags
}
